### ISSUE TITLE
Terminal with Japanese translation

### ISSUE THREAD

**Issue by alexmyczko** [gnustep/gap#7]
at https://github.com/gnustep/gap/tree/master/system-apps/Terminal
please add
https://github.com/Chubei-Nakagawa/gnustep_jp/tree/master/Terminal/Japanese.lproj

while doing so, maybe also add the rest?
https://github.com/Chubei-Nakagawa/gnustep_jp/tree/master/

**Comment by rmottola** [comment]
Terminal translation merged upstream on savannah. (Gworkspace done too)
